package com.mgplayer.tv.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFFFB86E)
val md_theme_dark_onPrimary = Color(0xFF492900)
val md_theme_dark_primaryContainer = Color(0xFF693C00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCBD)
val md_theme_dark_secondary = Color(0xFF8FCDFF)
val md_theme_dark_onSecondary = Color(0xFF003450)
val md_theme_dark_secondaryContainer = Color(0xFF004B71)
val md_theme_dark_onSecondaryContainer = Color(0xFFCBE6FF)
val md_theme_dark_tertiary = Color(0xFFFABD00)
val md_theme_dark_onTertiary = Color(0xFF3F2E00)
val md_theme_dark_tertiaryContainer = Color(0xFF5B4300)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDF9E)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF50453A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD5C3B5)
val md_theme_dark_outline = Color(0xFF9D8E81)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF8A5100)
val md_theme_dark_surfaceTint = Color(0xFFFFB86E)
val md_theme_dark_outlineVariant = Color(0xFF50453A)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFFF19100)
